apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: tekton-task
  namespace: my-apps
spec:
  params:
  - name: source-url
    type: string
  - name: source-revision
    type: string
  - default: ""
    name: sub-path
    type: string
  steps:
  - image: maven:3.8.6
    name: test
    script: |
      #!/bin/bash
          
      echo "SUBPATH=$(params.sub-path)"

      cd `mktemp -d`
      wget -qO- $(params.source-url) | tar xvz -m

      if [ "$(params.sub-path)" == "" ]; then
        mvn test --no-transfer-progress
      else 
        mvn test -am -pl $(params.sub-path) --no-transfer-progress
      fi
