---
apiVersion: carto.run/v1alpha1
kind: ClusterSourceTemplate
metadata:
  name: tekton-norunnable-task
spec:
  urlPath: .status.outputs.url
  revisionPath: .status.outputs.revision

  healthRule:
    singleConditionType: Succeeded

  template:
    apiVersion: tekton.dev/v1
    kind: TaskRun
    metadata:
      generateName: tekton-norunnable-task-run-
      labels:
        app.kubernetes.io/part-of: $(workload.metadata.name)$
    spec:
      taskRef:
        name: tekton-task
      params:
        - name: source-url
          value: $(source.url)$
        - name: source-revision
          value: $(source.revision)$
        - name: sub-path
          value: $(workload.spec.source.subPath)$

  urlPath: .spec.params[0].value
  revisionPath: .spec.params[1].value
  lifecycle: tekton
