apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: tekton-pipeline
  namespace: my-apps
spec:
  params:
  - name: source-url
    type: string
  - name: source-revision
    type: string
  - default: ""
    name: sub-path
    type: string
  tasks:
  - name: test
    params:
    - name: source-url
      value: $(params.source-url)
    - name: source-revision
      value: $(params.source-revision)
    - name: sub-path
      value: $(params.sub-path)
    taskSpec:
      metadata: {}
      params:
      - name: source-url
        type: string
      - name: source-revision
        type: string
      - name: sub-path
        type: string
      spec: null
      steps:
      - image: maven:3.8.6
        name: test
        script: |
          #!/bin/bash
          
          echo "SUBPATH=$(params.sub-path)"

          cd `mktemp -d`
          wget -qO- $(params.source-url) | tar xvz -m

          if [ "$(params.sub-path)" == "" ]; then
            mvn test --no-transfer-progress
          else 
            mvn test -am -pl $(params.sub-path) --no-transfer-progress
          fi
